### ISSUE TITLE
La paginación de episodios no funciona al filtrar por show

### ISSUE THREAD

**Issue by juandjara** [juandjara/dibujitos-api#1]
Cuando se piden episodios para un show, solo la primera página devuelve episodios. La propiedad `episodes` devuelta en el json es siempre un array vacio cuando se pide una página mayor que 0.
Esto ocurre aunque exista mas contenido que traerse de nyaa. Solo se recuperan los últimos 20 episodios mas recientes.

Ejemplo 1: https://nyapi.fuken.xyz/show/boruto-naruto-next-generations?page=1&meta=&source=hs
Ejemplo 2: https://nyapi.fuken.xyz/show/shingeki-no-bahamut-virgin-soul?page=1&meta=&source=hs

**Comment by ibaca** [comment]
El problema es que `(req.query.page || 0) + 1` termina traduciendose como `11` porque page es un string. Cambia la expresión por `+(req.query.page || 0) + 1`, seguramente mejor hacer lo mismo para rpp sea buena idea, o alguna otra forma mas JS friendly si existe (no suelo trabajar en js).
![image](https://user-images.githubusercontent.com/1042225/39155113-fdbca7ee-4750-11e8-9ce7-1f75ab5b6ce2.png)

**Comment by juandjara** [comment]
Perfecto. Esta tiene toda pinta de ser la fuente del error. Se podría hacer lo que sugieres. Mañana si saco un rato lo pruebo.
